name: freezed
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 0.13.0-nullsafety.2
homepage: https://github.com/nipun-solutelabs/freezed_b2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: 
  build:
  build_config:
  meta: 
  source_gen:
  freezed_annotation: 

dev_dependencies:
  json_serializable: 
  json_annotation: 
  build_test: 
  build_runner: 
  test: 
  matcher: 
  source_gen_test: 
